config/routes.rb
Store::Application.routes.draw do
  post "/add" => "items#add"
  resources :items
  #post '/add'
  root 'items#index'
  get '/cart' => "carts#show", as: "cart"
  post '/remove' => "carts#remove"
end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.last
    @items = Item.where(cart_id: @cart.id)
  end	

  def remove
    @item = Item.find(params[:id])
    @item.cart_id = nil

    @cart = Cart.find(session[:cart_id])
    @cart.total_price -= @item.price
    @cart.total_quantity -= 1

    @item.save && @cart.save

    redirect_to cart_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    # If there is already a cart for the session, don't create a new one
    session[:cart_id] = Cart.create(total_quantity: 0, total_price: 0) unless session[:cart_id].present?
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @cart = Cart.find_by(id: session[:cart_id])
    @random1 = Item.all.sample
    @random2 = Item.all.sample
    @random3 = Item.all.sample
  end

  def add
    @cart = Cart.find_by(id: session[:cart_id])
    @item = Item.find_by(id: params[:item_id])
    @item.cart_id = @cart.id

    if params[:quantity].present?
      @cart.total_price += @item.price * params[:quantity].to_i
      @cart.total_quantity += params[:quantity].to_i
    else
      @cart.total_price += @item.price
      @cart.total_quantity += 1
    end

    @item.save && @cart.save

    redirect_to cart_path
  end

  # GET /items/new
  def new
    @item = Item.new
    @cart = Cart.last
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:price, :name, :image, :item_number, :cart_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/carts/show.html.erb
<div class="container">
	<div class="col6">
		<% @items.each do |item| %>
			<div class="checkout-item">
			<%= image_tag(item.image, :class => "checkout-item-image") %>
			<%= link_to "Remove", "/remove?id=#{item.id}", method: "post", class: "delete-button" %>
		  <h3 class="cart-item-name"><%= item.name %></h3>
		  <h3 class="cart-item-price">$<%= item.price %>.00</h3>
		  <p class="itemquantity-checkout">Quantity:</p>
    	<%= form_tag '/add' do %>
      <%= select_tag(:quantity, options_for_select(1..20), :class=> "select") %>
      <%= hidden_field_tag(:item_id, params[:id]) %>
      <% end %>
		  </div>
		<% end %>
			
		<div class="summary">
      <ul>
        <li>Quantity: <%= @cart.total_quantity %></li>
        <li>Total price: $<%= @cart.total_price %>.00</li>
        <button>Checkout</button>
      </ul>
    </div>
	</div>
</div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :item_number %><br>
    <%= f.number_field :item_number %>
  </div>
  <div class="field">
    <%= f.hidden_field :cart_id %><br>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">
    <% @items.each do |item| %>
      <div class="item col4">
        <%= image_tag(item.image) %>
        <ul class="item-list">
          <li><%= item.name %></li>
        	<li class="itemprice">$<%= item.price %>.00</li>
        	<li><%= link_to 'Details', item %></li>
        	<li><%= link_to 'Add to cart', "/add?item_id=#{item.id}", method: 'post', class: "add" %></li>
        </ul>
      </div>
    <% end %>
  </div>
  <br>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="itempageimage">
  <%= image_tag(@item.image) %>
  </div>


  <div class="itemdetails">

    <p class="itemname">
      <strong><%= @item.name %></strong>
    </p>

    <p class="itemprice" style="display:inline">
      $<%= @item.price %>.00
    </p>

    <p class="itemnumber" style="display:inline">
      Item #: <%= @item.item_number %>
    </p>

    <p class="itemquantity">Quantity:</p>
    <%= form_tag '/add' do %>
      <%= select_tag(:quantity, options_for_select(1..20)) %>
      <%= hidden_field_tag(:item_id, params[:id]) %>

    <p class="itemdescription">
      <strong>Description:</strong>
      <%= @item.description %>
    </p>

    <%= submit_tag :submit, :value => "Add to cart",  class: "submitbutton" %>
    <% end %>
  </div>

  <ul class="relateditems">
    <li class="relateditem1"><%= @random1.name %>
    <%= image_tag(@random1.image) %></li>
    <li class="relateditem2"><%= @random2.name %>
    <%= image_tag(@random2.image) %></li>
    <li class="relateditem3"><%= @random3.name %>
    <%= image_tag(@random3.image) %></li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="nav">
      <ul class="navbar">
      	<li class="nav-item"><%= link_to "Home", root_path %></li> |
      	<li class="nav-item"><%= link_to "My Cart", cart_path %></li> |
        <li class="nav-item about">About</li>
        <% if controller.action_name == 'index' %>
      	<li class="nav-item cart">Drag onto me to add to cart! (<%= Cart.find(session[:cart_id]).total_quantity %>)</li>
        <% end %>
      </ul>
    </div>
    <%= yield %>

  </body>
</html>